export enum EnumResponseCode {
  USUARIO_CREADO_EXITOSAMENTE = 1,
  ERROR_CREAR_USUARIO,
  USUARIO_EXISTENTE,
  USUARIO_ACTUALIZADO_EXITOSAMENTE,
  ERROR_ACTUALIZAR_USUARIO,
  USUARIO_ELIMINADO_EXITOSAMENTE,
  ERROR_ELIMINAR_USUARIO,
  USUARIO_INEXISTENTE
}
